# Generated by Django 6.0 on 2025-12-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='print_colors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
