# Generated by Django 6.0 on 2025-12-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_print_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_price_per_kg', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('ink_price_per_kg', models.DecimalField(decimal_places=2, default=120000, max_digits=10)),
                ('lacquer_price_per_kg', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('plate_cost', models.DecimalField(decimal_places=2, default=40000, max_digits=10)),
                ('setup_cost', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('run_cost_per_box', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('profit_margin_percent', models.IntegerField(default=20)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=12800, max_digits=10)),
            ],
            options={
                'verbose_name': 'Pricing Settings',
                'verbose_name_plural': 'Pricing Settings',
            },
        ),
    ]
