# Generated by Django 6.0 on 2025-12-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pricingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paper_height',
            field=models.FloatField(blank=True, help_text='Paper Height (cm)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_width',
            field=models.FloatField(blank=True, help_text='Paper Width (cm)', null=True),
        ),
    ]
