# Generated by Django 6.0 on 2025-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_paper_height_order_paper_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=12800, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='ink_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=120000, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='lacquer_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='paper_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='plate_cost',
            field=models.DecimalField(decimal_places=2, default=40000, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='run_cost_per_box',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='setup_cost',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=20),
        ),
    ]
