# Generated by Django 6.0 on 2025-12-18 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_invoice_amount_alter_material_current_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='default_cutter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_cutter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='default_finisher_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_finisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='default_printer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_printer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='default_qc_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_qc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='default_warehouse_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_warehouse', to=settings.AUTH_USER_MODEL),
        ),
    ]
