# Generated by Django 6.0 on 2025-12-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transaction_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='cutting_type_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='print_colors_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='print_type_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='step',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('cutting', 'Cutting'), ('printing', 'Printing'), ('varnishing', 'Varnishing'), ('finishing', 'Finishing'), ('assembly', 'Assembly'), ('qc', 'QC')], max_length=20),
        ),
    ]
