# Generated by Django 6.0 on 2025-12-21 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_client_is_active_client_status_client_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mockup_url',
            field=models.URLField(blank=True, help_text='Dizayn maketi linki', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Ichki izohlar', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='responsible_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tannarx', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Yangi'), ('approved', 'Tasdiqlandi'), ('in_production', 'Ishlab chiqarishda'), ('ready', 'Tayyor (Sklad)'), ('delivered', 'Yetkazildi'), ('completed', 'Yakunlandi'), ('canceled', 'Bekor qilindi')], default='pending', max_length=20),
        ),
    ]
