# Generated by Django 6.0 on 2025-12-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_mockup_url_order_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstep',
            name='step',
            field=models.CharField(choices=[('queue', 'Navbatda'), ('cutting', 'Kesish'), ('printing', 'Chop etish'), ('gluing', 'Yelimlash'), ('drying', 'Quritish'), ('packaging', 'Qadoqlash'), ('ready', 'Tayyor (Sklad)')], max_length=20),
        ),
    ]
