# Generated by Django 6.0 on 2025-12-21 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_category_product_current_stock_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='warehouselog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='warehouselog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_logs', to='api.order'),
        ),
        migrations.AddField(
            model_name='warehouselog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouselog',
            name='type',
            field=models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim'), ('audit', 'Tuzatish (Audit)')], max_length=10),
        ),
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.material')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier')),
            ],
            options={
                'ordering': ['received_date'],
            },
        ),
        migrations.AddField(
            model_name='warehouselog',
            name='material_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.materialbatch'),
        ),
    ]
