# Generated by Django 6.0 on 2025-12-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_supplier_alter_warehouselog_options_material_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Buyurtma yakunlangan sana', null=True),
        ),
    ]
