# Generated by Django 6.0 on 2025-12-21 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='auto_update_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='machine_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=20),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='pricing_profiles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='tax_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='waste_percentage_ink',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='waste_percentage_lacquer',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='waste_percentage_paper',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='SettingsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
