# Generated by Django 6.0 on 2025-12-21 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pricingsettings_auto_update_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100, unique=True)),
                ('machine_type', models.CharField(choices=[('printer', 'Bosma stanok'), ('cutter', 'Kesish stanok'), ('laminator', 'Laminatsiya'), ('folder', 'Buklovchi'), ('other', 'Boshqa')], max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text="Soatlik narx (so'm)", max_digits=20)),
                ('setup_time_minutes', models.IntegerField(default=30, help_text='Sozlash vaqti (daqiqada)')),
                ('minimum_run_time_minutes', models.IntegerField(default=15, help_text='Minimal ish vaqti (daqiqada)')),
                ('compatible_processes', models.JSONField(blank=True, default=list, help_text="Mos jarayonlar ro'yxati")),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Machine Settings',
                'verbose_name_plural': 'Machine Settings',
                'ordering': ['machine_name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='pricing_profile',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Standard', 'Standard'), ('Wholesale', 'Wholesale')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='calculation_breakdown',
            field=models.JSONField(blank=True, help_text='Detailed cost breakdown', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pricing_profile_used',
            field=models.CharField(blank=True, default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='default_pricing_profile',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='enable_employee_efficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='payment_type_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='receipt_format_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='show_profit_to_client',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmployeeEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_stage', models.CharField(choices=[('cutting', 'Kesish'), ('printing', 'Chop etish'), ('gluing', 'Yelimlash'), ('drying', 'Quritish'), ('packaging', 'Qadoqlash'), ('finishing', 'Tayyorlash')], max_length=50)),
                ('units_per_hour', models.DecimalField(decimal_places=2, help_text='Bir soatda ishlab chiqarish qobiliyati (quti)', max_digits=10)),
                ('error_rate_percent', models.IntegerField(default=0, help_text='Xatolik foizi (0-100)')),
                ('hourly_labor_cost', models.DecimalField(decimal_places=2, help_text="Bir soatlik ish haqi (so'm)", max_digits=20)),
                ('effective_from', models.DateField(help_text='Qachondan kuchga kiradi')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Efficiency',
                'verbose_name_plural': 'Employee Efficiencies',
                'ordering': ['-effective_from'],
            },
        ),
    ]
