# Generated by Django 6.0 on 2026-01-01 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_machinesettings_client_pricing_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('is_working_day', models.BooleanField(default=True)),
                ('shift_count', models.IntegerField(default=1, help_text='Number of shifts on this day')),
                ('notes', models.TextField(blank=True, help_text='Holiday name or reason', null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Morning, Evening, Night', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Production capacity multiplier (1.0 = normal, 1.5 = 150% capacity)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_qty', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Reservation expires if order not started')),
                ('consumed', models.BooleanField(default=False, help_text='True when actually used in production')),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.material')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.materialbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_reservations', to='api.order')),
            ],
            options={
                'ordering': ['reserved_at'],
                'indexes': [models.Index(fields=['material', 'consumed'], name='api_reserva_materia_712b6b_idx'), models.Index(fields=['order', 'consumed'], name='api_reserva_order_i_8d436b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('order', 'Order'), ('pricing_settings', 'Pricing Settings'), ('production_step', 'Production Step'), ('material_batch', 'Material Batch')], max_length=50)),
                ('entity_id', models.CharField(help_text='UUID or ID of locked entity', max_length=255)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Auto-release after this time')),
                ('reason', models.CharField(default='editing', help_text='Why locked', max_length=255)),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks_held', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='api_systeml_entity__cc47e5_idx'), models.Index(fields=['expires_at'], name='api_systeml_expires_b9148b_idx')],
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
    ]
