# Generated by Django 6.0 on 2026-01-01 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_calendar_shift_reservation_systemlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='Price manually overridden by admin'),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_override_reason',
            field=models.TextField(blank=True, help_text='Why price was overridden', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_lock_snapshot',
            field=models.JSONField(blank=True, help_text='Full pricing data snapshot', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_lock_version',
            field=models.IntegerField(blank=True, help_text='PriceVersion used when locked', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_locked',
            field=models.BooleanField(default=False, help_text='If True, price cannot be recalculated'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='inventory_valuation_method',
            field=models.CharField(choices=[('fifo', 'FIFO'), ('average', 'Average'), ('last', 'Last Cost')], default='fifo', help_text='Method for calculating material costs', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='price_lock_enabled',
            field=models.BooleanField(default=True, help_text='Lock prices when order approved'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='scenario_pricing',
            field=models.JSONField(blank=True, default=dict, help_text='{"Standard": 1.0, "Express": 1.5, "Night": 1.3}'),
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., 1000, 2000, 3000', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., Cash, Accounts Receivable', max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset (Aktiv)'), ('liability', 'Liability (Passiv)'), ('equity', 'Equity (Kapital)'), ('revenue', 'Revenue (Daromad)'), ('expense', 'Expense (Xarajat)')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('entry_type', models.CharField(choices=[('payment', "To'lov"), ('purchase', 'Xarid'), ('sale', 'Sotuv'), ('adjustment', 'Tuzatish'), ('other', 'Boshqa')], max_length=20)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, help_text='e.g., Order #, Invoice #', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='api.order')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='api.transaction')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='api.chartofaccounts')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.journalentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('print_defect', 'Chop etish nuqsoni'), ('cutting_error', 'Kesishda xatolik'), ('gluing_issue', 'Yelimlash muammosi'), ('material_defect', 'Material nuqsoni'), ('design_error', 'Dizayn xatosi'), ('other', 'Boshqa')], max_length=50)),
                ('description', models.TextField(help_text='Muammoning batafsil tavsifi')),
                ('extra_material_cost', models.DecimalField(decimal_places=2, default=0, help_text="Qo'shimcha material xarajati", max_digits=20)),
                ('extra_labor_cost', models.DecimalField(decimal_places=2, default=0, help_text="Qo'shimcha ish haqi", max_digits=20)),
                ('extra_time_hours', models.DecimalField(decimal_places=2, default=0, help_text="Qo'shimcha vaqt (soat)", max_digits=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_detector', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_logs', to='api.order')),
                ('production_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productionstep')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_resolver', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('pricing_settings_snapshot', models.JSONField(help_text='Full PricingSettings dump')),
                ('formula_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('version_number',)},
            },
        ),
    ]
