# Generated by Django 6.0 on 2026-01-01 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_order_manual_override_order_manual_override_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('maintenance', 'Texnik xizmat'), ('breakdown', 'Buzilish'), ('repair', "Ta'mirlash"), ('cleaning', 'Tozalash'), ('calibration', 'Sozlash'), ('other', 'Boshqa')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Muammoning tavsifi', null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True if downtime is ongoing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='api.machinesettings')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_downtimes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_downtimes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
