# Generated by Django 6.0 on 2026-01-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_machinedowntime'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbatch',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
