# Generated by Django 6.0 on 2026-01-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_materialbatch_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, help_text='Warehouse color selection', max_length=100, null=True),
        ),
    ]
