# Generated by Django 6.0 on 2026-01-03 08:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_order_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('name', models.CharField(help_text="Template nomi, masalan: 'Dori qutisi standart'", max_length=255)),
                ('category', models.CharField(choices=[('medicine_box_1layer', 'Dori qutilari (1 qatlam)'), ('pizza_box', 'Pizza qutilari'), ('box_2layer', '2 qatlamli karobka'), ('box_3layer', '3 qatlamli karobka'), ('cookie_box', 'Pecheniye karobkalari'), ('gift_bag', "Sovg'a sumkalari"), ('food_box', 'Oziqa karobkalari'), ('custom', 'Maxsus')], max_length=50)),
                ('layer_count', models.IntegerField(default=1, help_text='Qatlamlar soni (1-3)')),
                ('default_waste_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Standart chiqindi foizi', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_width', models.FloatField(blank=True, help_text='Standart kenglik (cm)', null=True)),
                ('default_height', models.FloatField(blank=True, help_text='Standart balandlik (cm)', null=True)),
                ('default_depth', models.FloatField(blank=True, help_text='Standart chuqurlik (cm)', null=True)),
            ],
            options={
                'verbose_name': 'Product Template',
                'verbose_name_plural': 'Product Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialNormative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('material_type', models.CharField(choices=[('paper', 'Qogoz'), ('ink', 'Siyoh'), ('lacquer', 'Lak'), ('adhesive', 'Yelim'), ('other', 'Boshqa')], max_length=20)),
                ('color_count', models.IntegerField(blank=True, help_text='Ranglar soni (faqat siyoh uchun): 1, 2, 4, 6', null=True)),
                ('consumption_per_unit', models.DecimalField(decimal_places=4, help_text='Bir dona uchun sarflanish (g, ml, m²)', max_digits=20)),
                ('unit_of_measure', models.CharField(default='g', help_text="O'lchov birligi: g, ml, m², kg, L", max_length=20)),
                ('waste_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Chiqindi foizi', max_digits=5)),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Qachondan kuchga kiradi')),
                ('effective_to', models.DateField(blank=True, help_text='Qachongacha amal qiladi', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normatives', to='api.producttemplate')),
            ],
            options={
                'ordering': ['product_template', 'material_type', 'color_count'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplateLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('layer_number', models.IntegerField(help_text='Qatlam raqami (1, 2, 3)')),
                ('material_category', models.CharField(help_text='Material kategoriyasi: qogoz, karton, kraft, etc.', max_length=100)),
                ('min_density', models.IntegerField(blank=True, help_text='Minimal zichlik (gsm), masalan: 250', null=True)),
                ('max_density', models.IntegerField(blank=True, help_text='Maksimal zichlik (gsm), masalan: 400', null=True)),
                ('waste_percent_override', models.DecimalField(blank=True, decimal_places=2, help_text="Agar bo'lsa, template default waste ni override qiladi", max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('compatible_materials', models.ManyToManyField(blank=True, help_text='Ushbu qatlam uchun mos materiallar', related_name='template_layers', to='api.material')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='api.producttemplate')),
            ],
            options={
                'ordering': ['template', 'layer_number'],
                'unique_together': {('template', 'layer_number')},
            },
        ),
        migrations.CreateModel(
            name='ProductTemplateRouting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('sequence', models.IntegerField(help_text='Bosqich tartibi (1, 2, 3...)')),
                ('step_name', models.CharField(choices=[('design', 'Dizayn'), ('prepress', 'Pre-press'), ('cutting', 'Kesish'), ('printing', 'Chop etish'), ('lamination', 'Laminatsiya'), ('lacquering', 'Laklash'), ('die_cutting', 'Die-cutting'), ('gluing', 'Yelimlash'), ('folding', 'Buklash'), ('drying', 'Quritish'), ('packaging', 'Qadoqlash'), ('qc', 'Sifat nazorati')], max_length=50)),
                ('required_machine_type', models.CharField(blank=True, help_text='Kerakli stanok turi', max_length=50, null=True)),
                ('estimated_time_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Bir dona uchun taxminiy vaqt (daqiqa)', max_digits=10)),
                ('setup_time_minutes', models.IntegerField(default=0, help_text='Sozlash vaqti (daqiqa)')),
                ('qc_checkpoint', models.BooleanField(default=False, help_text='Ushbu bosqichdan keyin QC nazorati kerakmi?')),
                ('qc_checkpoint_criteria', models.TextField(blank=True, help_text='QC nazorati mezonlari', null=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Ixtiyoriy bosqichmi? (masalan: laklash)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_steps', to='api.producttemplate')),
            ],
            options={
                'ordering': ['template', 'sequence'],
                'unique_together': {('template', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='WorkerTimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('action', models.CharField(choices=[('start', 'START'), ('pause', 'PAUSE'), ('resume', 'RESUME'), ('finish', 'FINISH')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pause_reason', models.CharField(blank=True, choices=[('break', 'Tanaffus'), ('material_wait', 'Material kutish'), ('machine_issue', 'Stanok muammosi'), ('meeting', "Yig'ilish"), ('other', 'Boshqa')], help_text='Pauza sababi (faqat PAUSE action uchun)', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Ish joyi (masalan: Stanok #3)', max_length=100, null=True)),
                ('production_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='api.productionstep')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['production_step', 'timestamp'],
                'indexes': [models.Index(fields=['production_step', 'timestamp'], name='api_workert_product_170c82_idx'), models.Index(fields=['worker', 'timestamp'], name='api_workert_worker__e443ac_idx')],
            },
        ),
    ]
