# Generated by Django 6.0 on 2026-01-03 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_producttemplate_materialnormative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbatch',
            name='block_reason',
            field=models.TextField(blank=True, help_text='Bloklash sababi', null=True),
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='Bloklangan vaqt', null=True),
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='Kim bloklagan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='quality_status',
            field=models.CharField(choices=[('ok', 'OK'), ('blocked', 'Blocked'), ('quarantine', 'Quarantine')], default='ok', help_text='Sifat holati: OK, Blocked, Quarantine', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='material_suggestions',
            field=models.JSONField(blank=True, help_text='Alternative materials if primary unavailable', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='material_validation_passed',
            field=models.BooleanField(default=False, help_text='Material availability validated before approval'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_template',
            field=models.ForeignKey(blank=True, help_text='Product template used for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.producttemplate'),
        ),
    ]
