# Generated by Django 6.0 on 2026-01-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_materialbatch_block_reason_materialbatch_blocked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstep',
            name='actual_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Haqiqiy davomiylik (daqiqa)', null=True),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='depends_on_step',
            field=models.ForeignKey(blank=True, help_text="Ushbu bosqich qaysi bosqichga bog'liq", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_steps', to='api.productionstep'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='estimated_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Taxminiy davomiylik (daqiqa)', null=True),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='estimated_end',
            field=models.DateTimeField(blank=True, help_text='Taxminiy tugash vaqti', null=True),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='estimated_start',
            field=models.DateTimeField(blank=True, help_text='Taxminiy boshlanish vaqti', null=True),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Biriktirilgan stanok', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_steps', to='api.machinesettings'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='priority',
            field=models.IntegerField(default=5, help_text='Ustuvorlik darajasi (1=baland, 10=past)'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='queue_position',
            field=models.IntegerField(blank=True, help_text="Stanok navbatidagi o'rni", null=True),
        ),
    ]
