# Generated by Django 6.0 on 2026-01-04 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_productionstep_actual_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('checkpoint_name', models.CharField(max_length=255)),
                ('checkpoint_type', models.CharField(choices=[('visual', 'Vizual tekshiruv'), ('measurement', "O'lcham tekshiruvi"), ('functional', 'Funktsional test'), ('material', 'Material sifati'), ('finish', 'Yakuniy tekshiruv')], default='visual', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Bu checkpoint majburiyma?')),
                ('pass_criteria', models.TextField(help_text="O'tish mezonlari")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('pass', "O'tdi"), ('fail', "O'tmadi"), ('na', 'N/A')], db_index=True, default='pending', max_length=10)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, help_text="O'tmaganlik sababi", null=True)),
                ('defect_type', models.CharField(blank=True, choices=[('dimension', "O'lcham xato"), ('color', 'Rang xato'), ('damage', 'Shikastlangan'), ('alignment', "Noto'g'ri joylashish"), ('quality', 'Sifat past'), ('other', 'Boshqa')], max_length=20, null=True)),
                ('defect_severity', models.CharField(blank=True, choices=[('critical', 'Kritik'), ('major', 'Katta'), ('minor', 'Kichik')], max_length=10, null=True)),
                ('defect_count', models.IntegerField(blank=True, help_text='Nuqsonlar soni', null=True)),
                ('defect_photos', models.JSONField(blank=True, help_text="Rasm URL'lari (list)", null=True)),
                ('rework_triggered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inspector', models.ForeignKey(blank=True, limit_choices_to={'role': 'qc'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_inspections', to=settings.AUTH_USER_MODEL)),
                ('production_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_checkpoints', to='api.productionstep')),
                ('rework_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_from_qc', to='api.order')),
            ],
            options={
                'ordering': ['production_step', 'created_at'],
                'indexes': [models.Index(fields=['production_step', 'status'], name='api_qccheck_product_032b88_idx'), models.Index(fields=['inspector', 'inspected_at'], name='api_qccheck_inspect_f2e0b0_idx'), models.Index(fields=['status', 'created_at'], name='api_qccheck_status_5ebfc8_idx')],
            },
        ),
    ]
