# Generated by Django 6.0 on 2026-01-14 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_qc_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='is_parametric',
            field=models.BooleanField(default=False, help_text='If True, uses Engineering Engine logic (ParametricProfile)'),
        ),
        migrations.CreateModel(
            name='ParametricProductProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('version', models.IntegerField(default=1, help_text='Optimistic locking version')),
                ('geometry_script', models.JSONField(blank=True, default=dict, help_text='Formula logic for drawing 2D 3D model (e.g. cut_lines, safe_zone)')),
                ('min_width', models.FloatField(default=0, help_text='Minimum width supported (cm)')),
                ('max_width', models.FloatField(default=1000, help_text='Maximum width supported (cm)')),
                ('min_height', models.FloatField(default=0, help_text='Minimum height supported (cm)')),
                ('max_height', models.FloatField(default=1000, help_text='Maximum height supported (cm)')),
                ('parts_config', models.JSONField(blank=True, default=list, help_text='List of parts (e.g., [base, lid, insert])')),
                ('waste_logic_config', models.JSONField(blank=True, default=dict, help_text='Nesting algorithm and inter-item gap rules')),
                ('ink_density_estimated', models.DecimalField(decimal_places=2, default=250.0, help_text='Estimated ink coverage % (Standard CMYK total)', max_digits=5)),
                ('template', models.OneToOneField(help_text='Base template this profile enriches', on_delete=django.db.models.deletion.CASCADE, related_name='parametric_profile', to='api.producttemplate')),
            ],
            options={
                'verbose_name': 'Parametric Profile',
                'verbose_name_plural': 'Parametric Profiles',
            },
        ),
    ]
