# Generated by Django 6.0 on 2026-01-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_producttemplate_is_parametric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=10000000, help_text='Maksimal qarz limiti', max_digits=20),
        ),
    ]
