# Generated by Django 6.0 on 2026-01-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_client_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametricproductprofile',
            name='accessories',
            field=models.JSONField(blank=True, default=dict, help_text='Aksessuarlar: handles, eyelets, gluing_points'),
        ),
        migrations.AddField(
            model_name='parametricproductprofile',
            name='box_style',
            field=models.CharField(choices=[('custom', 'Custom'), ('pizza_box', 'Pizza Box (FEFCO 0427)'), ('shopping_bag', 'Shopping Bag')], default='custom', help_text='Avtomatik konstruktor turi', max_length=50),
        ),
    ]
