# Generated by Django 6.0 on 2026-01-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_parametricproductprofile_accessories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='base_die_cost',
            field=models.DecimalField(decimal_places=2, default=150000, help_text='Bazaviy qolip narxi (Taxta asosi)', max_digits=20),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='knife_price_per_meter',
            field=models.DecimalField(decimal_places=2, default=60000, help_text='Pichoqning 1 metri narxi (UZS)', max_digits=20),
        ),
    ]
