# Generated by Django 6.0 on 2026-01-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_pricingsettings_base_die_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='thickness_mm',
            field=models.FloatField(default=0, help_text='Material qalinligi (mm)'),
        ),
        migrations.AddField(
            model_name='material',
            name='weight_gsm',
            field=models.IntegerField(default=0, help_text="Og'irligi (g/m2)"),
        ),
    ]
