# Generated by Django 6.0 on 2026-01-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_material_thickness_mm_material_weight_gsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ink_coverage_percent',
            field=models.IntegerField(default=30, help_text='Siyoh bilan qoplanish foizi (0-100)'),
        ),
    ]
