# Generated by Django 6.0 on 2026-01-18 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_order_ink_coverage_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(default='mailer_box', help_text='e.g., mailer_box, pizza_box, bag', max_length=50)),
                ('dimensions', models.JSONField(default=dict, help_text='L, W, H, Thickness, etc.')),
                ('material_thickness', models.FloatField(default=3.0, help_text='Thickness in mm')),
                ('grain_direction', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=20)),
                ('dieline_svg', models.TextField(blank=True, help_text='Generated SVG path data', null=True)),
                ('uv_map_config', models.JSONField(blank=True, default=dict, help_text='Texture mapping config')),
                ('texture_map', models.JSONField(blank=True, default=dict, help_text='User uploaded logo positions')),
                ('nesting_layout', models.JSONField(blank=True, default=dict, help_text='Coordinates on standard sheet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='api.order')),
            ],
        ),
    ]
