# Generated by Django 5.1.3 on 2026-01-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_ordergeometry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstep',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='step',
            field=models.CharField(choices=[('queue', 'Navbatda'), ('prepress', 'Pre-press'), ('printing', 'Chop etish'), ('drying', 'Quritish'), ('lamination', 'Laminatsiya / Lak'), ('cutting', 'Kesish'), ('die_cutting', 'Shtans (Die-cut)'), ('gluing', 'Yelimlash / Buklash'), ('qc', 'Sifat Nazorati (QC)'), ('packaging', 'Qadoqlash'), ('ready', 'Tayyor (Sklad)'), ('dispatch', 'Yuklash / Topshirish')], max_length=20),
        ),
    ]
