# Generated by Django 5.1.3 on 2026-01-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_productionstep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='layout_description',
            field=models.CharField(blank=True, help_text='Masalan: 62x94 varaqda 8 ta (2x4)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waste_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Chiqindi % (Nesting natijasi)', max_digits=5, null=True),
        ),
    ]
