# Generated by Django 5.1.3 on 2026-01-20 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_order_layout_description_order_waste_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-deadline']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='DesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='designs/%Y/%m/')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved (Locked)'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_designs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_designs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_files', to='api.order')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('order', 'version')},
            },
        ),
    ]
