# Generated by Django 5.1.3 on 2026-01-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_order_options_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesettings',
            name='current_operating_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ishlagan soati', max_digits=10),
        ),
        migrations.AddField(
            model_name='machinesettings',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinesettings',
            name='maintenance_interval_hours',
            field=models.IntegerField(default=200, help_text="Moylash/Profilaktika oralig'i (soat)"),
        ),
    ]
