# Generated by Django 5.1.3 on 2026-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_machinesettings_current_operating_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='setup_waste_sheets',
            field=models.IntegerField(default=20, help_text='Stanok sozlash uchun ketadigan varaqlar (dona)'),
        ),
    ]
