# Generated by Django 5.1.3 on 2026-01-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_pricingsettings_setup_waste_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent (Overdrive)')], default='normal', help_text='Order priority for scheduling', max_length=20),
        ),
    ]
