# Generated by Django 5.1.3 on 2026-03-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_order_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_name',
            field=models.CharField(blank=True, help_text='Kitob nomi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cover_type',
            field=models.CharField(blank=True, help_text='Muqova turi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='page_count',
            field=models.IntegerField(blank=True, help_text='Betlar soni', null=True),
        ),
    ]
