# Generated by Django 5.1.3 on 2026-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_order_book_name_order_cover_type_order_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('problem', 'Problem / Blocked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='step',
            field=models.CharField(choices=[('queue', 'Navbatda'), ('prepress', 'Prepress (maket)'), ('printing_internal', 'Bosma (ichki sahifalar)'), ('printing_cover', 'Bosma (muqova)'), ('folding', 'Faltsovka (buklash)'), ('assembly', "Yig'ish (to'plash)"), ('binding', 'Termokley / Tikish'), ('trimming', 'Uch tomondan kesish'), ('printing', 'Chop etish (Universal)'), ('drying', 'Quritish'), ('lamination', 'Laminatsiya / Lak'), ('cutting', 'Kesish'), ('die_cutting', 'Shtans (Die-cut)'), ('gluing', 'Yelimlash'), ('qc', 'Sifat Nazorati (QC)'), ('packaging', 'Qadoqlash'), ('ready', 'Tayyor (Sklad)'), ('dispatch', 'Yuklash / Topshirish')], max_length=20),
        ),
    ]
