# Generated by Django 5.1.3 on 2026-03-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_productionstep_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reason', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_entries', to='api.material')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
