# Generated by Django 5.1.3 on 2026-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Oylik (1-12)')),
                ('year', models.IntegerField(help_text='Yil (masalan 2026)')),
                ('plan_amount', models.DecimalField(decimal_places=2, help_text='Rejalashtirilgan summa', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oylik Reja',
                'verbose_name_plural': 'Oylik Rejalar',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
