# Generated by Django 5.1.3 on 2026-03-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_monthlyplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker (Ishchi)'), ('project_manager', 'Project Manager'), ('warehouse', 'Warehouse'), ('cutter', 'Cutter'), ('printer', 'Printer'), ('finishing', 'Finishing'), ('qc', 'QC'), ('accountant', 'Accountant')], default='project_manager', max_length=20),
        ),
    ]
