# Generated by Django 5.1.3 on 2026-03-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='materialbatch',
            name='cost_per_unit',
        ),
    ]
