# Generated by Django 5.1.3 on 2026-03-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_material_price_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
