# Generated by Django 5.1.3 on 2026-03-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_user_phone_user_status_user_telegram_id_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vaziyatga qarab olingan avans', max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', "To'lanmagan"), ('partially_paid', 'Avans olingan'), ('fully_paid', "To'liq to'langan")], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_transactions', to='api.order'),
        ),
    ]
