# Generated by Django 5.1.3 on 2026-03-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_order_advance_payment_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initial_payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Pul o'tkazish")], default='cash', help_text="Avans qanday to'langani", max_length=20),
        ),
    ]
