# Generated by Django 5.1.3 on 2026-03-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_task_completed_at_task_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstep',
            name='defect_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='produced_qty',
            field=models.IntegerField(default=0),
        ),
    ]
