# Generated by Django 5.1.3 on 2026-03-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_productionstep_defect_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productionstep',
            options={'ordering': ['order', 'sequence', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='productionstep',
            name='depends_on_step',
        ),
        migrations.AddField(
            model_name='productionstep',
            name='input_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='step',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.productiontemplate'),
        ),
        migrations.CreateModel(
            name='TemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.productiontemplate')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('template', 'sequence')},
            },
        ),
    ]
