# Generated by Django 5.1.3 on 2026-03-13 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_productiontemplate_alter_productionstep_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_qty', models.IntegerField(default=0)),
                ('defect_qty', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='api.productionstep')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ishlab chiqarish logi',
                'verbose_name_plural': 'Ishlab chiqarish loglari',
                'ordering': ['-created_at'],
            },
        ),
    ]
