# Generated by Django 5.1.3 on 2026-03-14 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_attendance_break_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
