# Generated by Django 5.1.3 on 2026-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_transaction_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_target',
            field=models.IntegerField(default=1000, help_text='Kunlik reja (mahsulot soni)'),
        ),
        migrations.AddField(
            model_name='user',
            name='quality_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
    ]
