# Generated by Django 5.1.3 on 2026-03-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_user_daily_target_user_quality_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='binding_type',
            field=models.CharField(blank=True, help_text="Bog'lash turi (Yelim, Skoba, va h.k.)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='cover_weight',
            field=models.IntegerField(blank=True, help_text="Muqova qog'oz grammaji (gsm)", null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='format',
            field=models.CharField(blank=True, help_text='Format (masalan: A4, A5)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='lamination',
            field=models.CharField(blank=True, help_text='Laminatsiya turi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='page_count',
            field=models.IntegerField(blank=True, help_text='Sahifalar soni', null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='paper_type',
            field=models.CharField(blank=True, help_text="Qog'oz turi", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='paper_weight',
            field=models.IntegerField(blank=True, help_text="Ichki qog'oz grammaji (gsm)", null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='print_type',
            field=models.CharField(blank=True, help_text='Bosma turi (1+1, 4+4)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Plastik'), ('bank', "Bank o'tkazma")], default='cash', help_text="Avans qanday to'langani", max_length=20),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='category',
            field=models.CharField(choices=[('medicine_box_1layer', 'Dori qutilari (1 qatlam)'), ('pizza_box', 'Pizza qutilari'), ('box_2layer', '2 qatlamli karobka'), ('box_3layer', '3 qatlamli karobka'), ('cookie_box', 'Pecheniye karobkalari'), ('gift_bag', "Sovg'a sumkalari"), ('food_box', 'Oziqa karobkalari'), ('book', 'Kitob'), ('magazine', 'Jurnal'), ('brochure', 'Broshyura'), ('catalog', 'Katalog'), ('booklet', 'Buklet'), ('custom', 'Maxsus')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Plastik'), ('bank', "Bank o'tkazma")], default='cash', max_length=20),
        ),
    ]
