# Generated by Django 5.1.3 on 2026-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_producttemplate_binding_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='binding_type',
            field=models.CharField(blank=True, help_text="Bog'lash turi", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cover_weight',
            field=models.IntegerField(blank=True, help_text='Muqova grammaji', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='format',
            field=models.CharField(blank=True, help_text='Format (A5, A4, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lamination',
            field=models.CharField(blank=True, help_text='Laminatsiya', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_weight',
            field=models.IntegerField(blank=True, help_text="Qog'oz grammaji", null=True),
        ),
    ]
