# Generated by Django 5.1.3 on 2026-03-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_order_binding_type_order_cover_weight_order_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='bleed_mm',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Bleed (mm)', max_digits=5),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='column_count',
            field=models.IntegerField(default=1, help_text='Grid ustunlari soni'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='margin_bottom_mm',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Pastki margin (mm)', max_digits=5),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='margin_inner_mm',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Ichki margin / Gutter (mm)', max_digits=5),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='margin_outer_mm',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Tashqi margin (mm)', max_digits=5),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='margin_top_mm',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Yuqori margin (mm)', max_digits=5),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='safe_area_padding_mm',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Safe area padding (mm)', max_digits=5),
        ),
    ]
