# Generated by Django 5.1.3 on 2026-03-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_producttemplate_bleed_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sotilish narxi (1 dona)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tan narxi (Jami)', max_digits=20, null=True),
        ),
    ]
