# Generated by Django 5.1.3 on 2026-03-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_order_price_per_unit_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatestage',
            name='auto_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatestage',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='templatestage',
            name='estimated_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatestage',
            name='machine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='templatestage',
            name='requires_operator',
            field=models.BooleanField(default=True),
        ),
    ]
