# Generated by Django 5.1.3 on 2026-03-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_templatestage_auto_start_templatestage_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstep',
            name='auto_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='estimated_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='requires_operator',
            field=models.BooleanField(default=True),
        ),
    ]
