# Generated by Django 5.1.3 on 2026-03-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_productionstep_auto_start_productionstep_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttemplaterouting',
            name='required_machine_type',
        ),
        migrations.AddField(
            model_name='producttemplaterouting',
            name='auto_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttemplaterouting',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttemplaterouting',
            name='estimated_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttemplaterouting',
            name='machine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttemplaterouting',
            name='requires_operator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producttemplaterouting',
            name='stage_name',
            field=models.CharField(default='Default Stage', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttemplaterouting',
            name='step_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
