# Generated by Django 5.1.3 on 2026-03-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_producttemplaterouting_required_machine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='defect_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='produced_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='defect_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='input_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='produced_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
