# Generated by Django 5.1.3 on 2026-03-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_productionlog_defect_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Mijozga topshirilgan sana', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Ishlab chiqarish yakunlangan sana', null=True),
        ),
    ]
