# Generated by Django 5.1.3 on 2026-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_order_delivered_at_alter_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='defect_pages',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='produced_pages',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker (Ishchi)')], default='worker', max_length=20),
        ),
    ]
