# Generated by Django 5.1.3 on 2026-03-21 21:27

import django.db.models.deletion
from django.db import migrations, models

def create_units_and_map(apps, schema_editor):
    Material = apps.get_model('api', 'Material')
    Unit = apps.get_model('api', 'Unit')
    
    # Find all unique string units currently in Material
    for mat in Material.objects.all():
        old_unit = getattr(mat, 'unit', None)
        if old_unit and isinstance(old_unit, str) and old_unit.strip() and not old_unit.isdigit():
            # It's a string like "pcs" or "kg"
            unit_name = old_unit.strip()
            unit_obj, created = Unit.objects.get_or_create(
                name=unit_name,
                defaults={'code': unit_name[:20].lower().replace(' ', '_'), 'is_base': True}
            )
            # Store the integer ID back as a string so SQLite has the correct foreign key reference
            mat.unit = str(unit_obj.id)
            mat.save(update_fields=['unit'])
        elif old_unit == "":
            mat.unit = None
            mat.save(update_fields=['unit'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_productionlog_defect_pages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_base', models.BooleanField(default=False, help_text="Is this a base unit like 'dona' or 'kg'?")),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='version',
            field=models.IntegerField(default=1, help_text='Optimistic locking version'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='version',
            field=models.IntegerField(default=1, help_text='Optimistic locking version'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.IntegerField(default=1, help_text='Optimistic locking version'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='materialnormative',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametricproductprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producttemplatelayer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producttemplaterouting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qccheckpoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workertimelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(create_units_and_map, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unit'),
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=4, max_digits=12)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='api.unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='api.unit')),
            ],
        ),
    ]
