# Generated by Django 5.1.3 on 2026-03-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_transaction_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbatch',
            name='received_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
