# Generated by Django 5.1.3 on 2026-03-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_materialbatch_received_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='packs_per_box',
            field=models.PositiveIntegerField(default=5, help_text='Number of packs in one box (yashik)'),
        ),
        migrations.AddField(
            model_name='material',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=500, help_text='Number of units in one pack (pachka)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
