# Generated by Django 5.1.3 on 2026-03-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_material_packs_per_box_material_units_per_pack_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
